Extracted sources to repositories
Fixed bugs

diff --git a/scripts/xmfw-install b/scripts/xmfw-install
--- a/scripts/xmfw-install
+++ b/scripts/xmfw-install
@@ -12,7 +12,9 @@ bold="\e[1m"
 reset="\e[0m"
 
 vlog() {
-	[ "$verbose" == "yes" ] && echo -e " > $1$reset" >&2
+	if [ "$verbose" == "yes" ]; then
+		echo -e " > $1$reset" >&2
+	fi
 }
 
 error() {
@@ -29,6 +31,7 @@ info() {
 
 usage() {
 	printf "Usage: xmfw-install [-mvc] " >&2
+	printf "[-a architecture] " >&2
 	printf "[-i CONFIG_IMPORT_PATH] " >&2
 	printf "[-o CONFIG_EXPORT_PATH] " >&2
 	printf "<xtratum build image> [system base image]\n" >&2
@@ -44,16 +47,18 @@ cleanup() {
 	vlog "Cleaning up..."
 
 	if [ -n "$build_cont" ]; then
-		docker rm $build_cont
+		docker rm --force $build_cont >/dev/null
 	fi
 
 	if [ -n "$system_cont" ]; then
-		docker rm $system_cont
+		docker rm --force $system_cont >/dev/null
 	fi
 
 	if [ -n "$tmpdir" ]; then
-		rm -r $tmpdir
+		rm -rf $tmpdir
 	fi
+
+	return 0
 }
 
 trap cleanup 0 1 2 3 6 15
@@ -113,7 +118,7 @@ ask_toolchain() {
 	case $toolchain_bin in
 		/*) 
 			if [ -z "$(echo "$toolchain_bin" | grep "$toolchain")" ]; then
-				error "Toolchain binaries path $toolchain is not in toolchain path $toolchain!"
+				error "Toolchain binaries path $toolchain_bin is not in toolchain path $toolchain!"
 				exit 1
 			fi
 
@@ -150,11 +155,21 @@ check_image_name() {
 	xmfw=${image_name#*/}
 	xmfw=${xmfw%:*}
 
-	if ! [[ "$xmfw" == "xmfw" ]]; then
-		return 1;
-	else
+	if [[ "$xmfw" == "xmfw" ]]; then
 		return 0;
+	else
+		error "Image $build_image does not follow the naming convention."
+		error "If you are$bold really$reset$red sure that it is an image valid to use with xmfw, please rename it to the format ${bold}[repo/]xmfw:[x.y.z][-arch][-name]$reset"
+		return 1;
 	fi
+}
+
+check_image_exists() {
+	[ -n "$(docker image ls --quiet --filter "reference=$1")" ]
+}
+
+check_container_exists() {
+	[ -n "$(docker ps --all --quiet --filter "name=$1")" ]
 }
 
 # ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## 
@@ -176,10 +191,6 @@ build() {
 		ask_toolchain
 	fi
 
-
-	# architecture
-	arch=
-
 	# flag activating export
 	expflag=
 
@@ -190,8 +201,15 @@ build() {
 	toolchain_opt=
 
 	# extract arch from conventional name
-	arch=${build_image#*:*-}
-	arch=${arch%%-*}
+	if [ -z "$arch" ]; then
+		arch=${build_image#*:*-}
+		arch=${arch%%-*}
+	fi
+
+	if [ -z "$arch" ]; then
+		error "Could not find target architecture! Please specify it with the ${bold}-a$reset option"
+		return 1
+	fi
 
 	# if the toolchain has not been specified, don't specify it in the
 	# config options so that the container's default toolchain is used
@@ -215,11 +233,11 @@ build() {
 
 	# build confic cli
 	printf -v ccli "config -a %s %s %s %s %s" \
-		$arch \
-		$toolchain_opt \
-		$impflag \
-		$expflag \
-		$menu
+		"$arch" \
+		"$toolchain_opt" \
+		"$impflag" \
+		"$expflag" \
+		"$menu"
 
 	# if config-only, do not call build
 	# TODO does not work on ia32
@@ -279,7 +297,7 @@ install() {
 	# if the system base image is a xtratum build image,
 	# choose conventional name;
 	# else, name the system build image according to its base
-	if check_image_name $system_image; then
+	if check_image_name $system_image 2>/dev/null; then
 		system_image="xmfw-system:${build_image#*:}"
 	else
 		system_image="xmfw-$(echo $system_image | sed 's/:/-/g')-system:${build_image#*:}"
@@ -300,6 +318,8 @@ install() {
 
 	vlog "Creating final image"
 	docker commit $system_cont "$system_image" || return 1
+
+	return 0
 }
 
 # ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## 
@@ -309,10 +329,11 @@ install() {
 ## Main script flow
 
 # Options
-while getopts mcvi:o: opt; do
+while getopts mcva:i:o: opt; do
 	case $opt in
 		m) menu="menu" ;;
 		v) verbose="yes" ;;
+		a) arch="$OPTARG" ;;
 		i) import_config="$OPTARG" ;;
 		o) export_config="$OPTARG" ;;
 		c) config="yes" ;;
@@ -335,22 +356,43 @@ if [ "$config" == "yes" ]; then
 	fi
 fi
 
+# check config arguments
+if [ -n "$export_config" ] && ! [ -d "$(dirname "$export_config")" ]; then
+	error "Destination directory $(dirname $export_config) does not exist";
+	exit 2
+fi
+
+# check config arguments
+if [ -n "$import_config" ] && ! [ -e "$import_config" ]; then
+	error "File $import_config does not exist";
+	exit 2
+fi
+
 # check that build image argument is present
 if [ -z "$build_image" ]; then
 	usage 
 	exit 2
 fi
 
+# check that build image exists
+if ! check_image_exists "$build_image"; then
+	error "Image $build_image is not present in this computer"
+	warn  "Please pull it first using: ${bold}docker pull $build_image"
+	exit 2
+fi
+
 # check convention on build image
 if ! check_image_name "$build_image"; then
-	error "Image $build_image does not follow the naming convention."
-	error "If you are$bold really$reset$red sure that it is an image valid to use with xmfw, please rename it to the format ${bold}[repo/]xmfw:[x.y.z]-[arch][-name]$reset"
 	exit 2
 fi
 
 # if system image is not specified, use build image
 if [ -z "$system_image" ]; then
 	system_image="$build_image";
+elif ! check_image_exists "$system_image"; then
+	error "Image $system_image is not present in this computer"
+	warn  "Please pull it first using: ${bold}docker pull $system_image"
+	exit 2
 fi
 
 tmpdir=$(mktemp -d)
@@ -360,5 +402,9 @@ build   || { error 'XtratuM could not build! Have you set up your toolchain corr
 if [ "$config" != "yes" ]; then
 	install || { error 'There was an error during instalation!'; exit 1; }
 fi
+
+info "$bold Success!"
+
+exit 0
 
 # ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## 
diff --git a/scripts/xmfw-system b/scripts/xmfw-system
--- a/scripts/xmfw-system
+++ b/scripts/xmfw-system
@@ -16,11 +16,13 @@ system_build=
 
 toolchain=
 
-keep_container="no"
+keep_container="yes"
 keep_path="yes"
 
 vlog() {
-	[ "$verbose" == "yes" ] && echo -e " > $1$reset" >&2
+	if [ "$verbose" == "yes" ]; then
+		echo -e " > $1$reset" >&2
+	fi
 }
 
 error() {
@@ -39,7 +41,7 @@ cleanup() {
 	vlog "Cleaning up..."
 
 	if [ -n "$system_build" ] && [ "$keep_container" != "yes" ]; then
-		docker rm $system_build
+		docker rm --force $system_build >/dev/null
 	fi
 
 	if [ -n "$system_path" ] && [ "$keep_path" != "yes" ]; then
@@ -105,14 +107,33 @@ ask_toolchain() {
 
 name_from_path() {
 	basename "$(readlink -f "$1")"
+
 }
 
-check_container() {
-	if [ -z "$(docker ps --all --quiet --filter "name=$system_build")" ]; then
-		return 1;
-	else
+
+check_system_image_name() {
+	image_name="$1"
+
+	# name of the container. must be ``xmfw-system'' or ``xmfw-name-system''
+	# repository and tags are stripped
+	xmfw=${image_name#*/}
+	xmfw=${image_name%:*}
+
+	if [[ "$xmfw" == "xmfw-system" || "$xmfw" =~ "xmfw-*-system" ]] ; then
 		return 0;
+	else
+		error "Image $build_image does not follow the naming convention."
+		error "If you are$bold really$reset$red sure that it is an image valid to use with xmfw, please rename it to the format ${bold}[repo/]xmfw:[x.y.z]-[arch][-name]$reset"
+		return 1;
 	fi
+}
+
+check_image_exists() {
+	[ -n "$(docker image ls --quiet --filter "reference=$1")" ]
+}
+
+check_container_exists() {
+	[ -n "$(docker ps --all --quiet --filter "name=$1")" ]
 }
 
 create_container() {
@@ -134,35 +155,37 @@ create_container() {
 	vlog "Creating intermediate container"
 	docker create --name $system_build \
 		$toolchain_mount \
-		-it $system_image $cmdline || return 1
+		-it $system_image $cmdline >/dev/null || return 1
+
+	keep_container="no"
 
 	vlog "Installing XtratuM"
-	docker start -i $system_build || return 1
+	docker start -i $system_build >/dev/null || return 1
 
 	vlog "Creating final container"
 	system_image=$(docker commit $system_build || return 1)
 
 	info "Creating default system in $bold$system_path"
-	docker cp $system_build:/usr/share/defaults/systems/default_sys/ $system_path || return 1
+	docker cp $system_build:/opt/xm/xal-examples/$template $system_path || return 1
 
-	docker rm $system_build || return 1
+	docker rm $system_build >/dev/null || return 1
 
 	docker create --name $system_build \
 		$toolchain_mount \
 		-v "$(readlink -f "$system_path")":/opt/system \
 		-it $system_image \
-		sh -c "make -C /opt/system 'XAL_PATH=/opt/xm/xal' 'XTRATUM_PATH=/opt/xm/xm' resident_sw" || return 1
+		sh -c "make -C /opt/system 'XAL_PATH=/opt/xm/xal' 'XTRATUM_PATH=/opt/xm/xm' resident_sw" >/dev/null || return 1
 }
 
 create() {
-	keep_container="no"
-	keep_path="no"
+	if [ ! -d "$(dirname "${system_path%/}")" ]; then
+		error "$(dirname "${system_path%/}") is not a directory!"
+		return 1
+	fi
 
-	mkdir -p "$(dirname "${system_path%/}")"
-
-	if check_container; then
+	if check_container_exists $system_build; then
 		warn "There is already a container named $system_build, recreating..."
-		docker rm $system_build
+		docker rm $system_build >/dev/null
 	fi
 
 	create_container || return 1
@@ -170,17 +193,27 @@ create() {
 
 build() {
 
-	if ! check_container; then
+	if ! check_container_exists $system_build; then
 		warn "The container for $bold$system_name$reset$yellow ($system_build) has not been created"
 		warn "Creating..."
 
 		read -p 'Specify the system install image: ' system_image
 
+		if ! check_system_image_name $system_image; then
+			return 1
+		fi
+
 		create_container
 	fi
 
 	info "Building $bold$system_path$reset$green using $bold$system_build$reset$green"
-	docker start -i $system_build
+	docker start -i $system_build >/dev/null
+}
+
+list_templates() {
+	container=$(docker create -it "$system_image" /opt/xm-install --tar tf)
+	docker start -i $container | sed -n 's,./xal-examples/\(.*\)/.*,\1,p' | sort | uniq
+	docker rm $container >/dev/null
 }
 
 while getopts v opt; do
@@ -195,9 +228,23 @@ cmd="$1"
 shift 1 || true
 
 case "$cmd" in
+	templates)
+		system_image="$1"
+		if [ -z "$system_image" ]; then
+			usage
+			exit 1
+		fi
+
+		if ! check_system_image_name $system_image; then
+			exit 2
+		fi
+
+		list_templates
+		;;
 	create)
 		system_image="$1"
 		system_path="$2"
+		template="$3"
 		system_name="$(basename "$system_path")"
 		system_build="xmfw-$system_name-build"
 
@@ -212,7 +259,25 @@ case "$cmd" in
 			exit 1
 		fi
 
-		create || error "Error creating system!"
+		if ! check_system_image_name $system_image; then
+			exit 2
+		fi
+
+		if [ -z "$template" ]; then
+			template_list="$(list_templates)"
+			while true; do
+				warn "You must choose a valid template. These are available:"
+				echo -e "$template_list"
+				read -p 'Template name: ' template || exit 1
+				if [ -z "$template" ] || [ -z "$(echo "$template_list" | grep "$template")" ]; then
+					warn "Template name not valid"
+				else
+					break
+				fi
+			done
+		fi
+
+		create || { error "Error creating system!"; exit 1; }
 		;;
 	build) 
 		system_path="$1"
@@ -225,7 +290,7 @@ case "$cmd" in
 			exit 1
 		fi
 
-		build || error "Error building system!"
+		build || { error "Error building system!"; exit 1; }
 		;;
 	*)
 		usage
